chore: Update Docker swarm join command to use hyperion overlay network

diff --git a/actions/deploy-service/member/action.yaml b/actions/deploy-service/member/action.yaml
--- a/actions/deploy-service/member/action.yaml
+++ b/actions/deploy-service/member/action.yaml
@@ -73,7 +73,19 @@ runs:
     - name: Join Docker Swarm Network
       shell: bash
       run: |
+        TOKEN=$(infisical secrets get DOCKER_SWARM_MANAGER_TOKEN --token $INFISICAL_TOKEN --projectId ${{ inputs.project_id }} --plain)
+        if [ -z "$TOKEN" ]; then
+          echo "Failed to retrieve Docker Swarm Manager token from Infisical."
+          exit 1
+        fi
+        echo "Retrieved Swarm Join Token successfully: $TOKEN"
+        
+        # Debug output for manager IP
+        echo "Manager IP: ${{ inputs.manager_ip }}"
+
         docker swarm join --token $TOKEN ${{ inputs.manager_ip }}:2377
+      env:
+        INFISICAL_TOKEN: ${{ env.INFISICAL_TOKEN }}
 
     - name: Deploy Service as Docker Swarm Member
       shell: bash
@@ -87,11 +99,6 @@ runs:
             --mount type=volume,source=pgdata,target=/var/lib/postgresql/data \
             -p 5433:5432 \
             ${{ inputs.docker_image }}
-        else
-          docker service create --name service \
-            --network hyperion \
-            ${{ inputs.docker_image }}
-        fi
 
     - name: Check if Service is Running
       shell: bash
