chore: Retrieve Swarm Join Token and CA Fingerprint from Infisical

diff --git a/actions/deploy-service/member/action.yaml b/actions/deploy-service/member/action.yaml
--- a/actions/deploy-service/member/action.yaml
+++ b/actions/deploy-service/member/action.yaml
@@ -78,24 +78,32 @@ runs:
         fi
         echo "INFISICAL_TOKEN=$INFISICAL_TOKEN" >> $GITHUB_ENV
 
-    - name: Retrieve Swarm Join Token from Infisical
+    - name: Retrieve Swarm Join Token and CA Fingerprint from Infisical
       shell: bash
       run: |
         set -e
-        TOKEN=$(infisical secrets get DOCKER_SWARM_MANAGER_TOKEN --token $INFISICAL_TOKEN --projectId ${{ inputs.project_id }} --plain)
-        if [ -z "$TOKEN" ]; then
+        SWARM_JOIN_TOKEN=$(infisical secrets get DOCKER_SWARM_MANAGER_TOKEN --token $INFISICAL_TOKEN --projectId ${{ inputs.project_id }} --plain)
+        if [ -z "$SWARM_JOIN_TOKEN" ]; then
           echo "Failed to retrieve Docker Swarm Manager token from Infisical."
           exit 1
         fi
         echo "Retrieved Swarm Join Token successfully."
-        echo "SWARM_JOIN_TOKEN=$TOKEN" >> $GITHUB_ENV
+        echo "SWARM_JOIN_TOKEN=$SWARM_JOIN_TOKEN" >> $GITHUB_ENV
+
+        CA_FINGERPRINT=$(infisical secrets get DOCKER_SWARM_CA_FINGERPRINT --token $INFISICAL_TOKEN --projectId ${{ inputs.project_id }} --plain)
+        if [ -z "$CA_FINGERPRINT" ]; then
+          echo "Failed to retrieve CA fingerprint from Infisical."
+          exit 1
+        fi
+        echo "Retrieved CA fingerprint successfully."
+        echo "CA_FINGERPRINT=$CA_FINGERPRINT" >> $GITHUB_ENV
 
     - name: Join Docker Swarm Network
       shell: bash
       run: |
         set -e
-        echo "Joining Docker Swarm with token: $SWARM_JOIN_TOKEN"
-        docker swarm join --token $SWARM_JOIN_TOKEN ${{ inputs.manager_ip }}:2377
+        echo "Joining Docker Swarm with token: $SWARM_JOIN_TOKEN and fingerprint: $CA_FINGERPRINT"
+        docker swarm join --token $SWARM_JOIN_TOKEN --ca-hash sha256:$CA_FINGERPRINT ${{ inputs.manager_ip }}:2377
 
     - name: Deploy Service as Docker Swarm Member
       shell: bash
