chore: Update Docker swarm join command to retrieve CA Fingerprint from Docker info

diff --git a/actions/deploy-service/manager/action.yaml b/actions/deploy-service/manager/action.yaml
--- a/actions/deploy-service/manager/action.yaml
+++ b/actions/deploy-service/manager/action.yaml
@@ -60,11 +60,16 @@ runs:
         docker swarm init
         echo "MANAGER_TOKEN=$(docker swarm join-token -q manager)" >> $GITHUB_ENV
 
-    # New Step: Retrieve CA Fingerprint
+    # Updated Step: Retrieve CA Fingerprint
     - name: Retrieve Docker Swarm CA Fingerprint
       shell: bash
       run: |
-        CA_FINGERPRINT=$(docker swarm ca --fingerprint | awk '{print $2}')
+        set -e
+        CA_FINGERPRINT=$(docker info --format '{{.Swarm.Cluster.TLSInfo.TrustRoot}}' | openssl x509 -noout -fingerprint -sha256 | sed 's/.*=//')
+        if [ -z "$CA_FINGERPRINT" ]; then
+          echo "Failed to retrieve CA Fingerprint."
+          exit 1
+        fi
         echo "CA_FINGERPRINT=$CA_FINGERPRINT" >> $GITHUB_ENV
 
     - name: Save Swarm Join Token to Infisical
@@ -72,7 +77,6 @@ runs:
       run: |
         infisical secrets set DOCKER_SWARM_MANAGER_TOKEN="${{ env.MANAGER_TOKEN }}" --token $INFISICAL_TOKEN --projectId ${{ inputs.project_id }}
 
-    # New Step: Save CA Fingerprint to Infisical
     - name: Save CA Fingerprint to Infisical
       shell: bash
       run: |
