chore: Update Docker setup to remove conflicting packages and fix broken packages

diff --git a/actions/deploy-service/manager/action.yaml b/actions/deploy-service/manager/action.yaml
--- a/actions/deploy-service/manager/action.yaml
+++ b/actions/deploy-service/manager/action.yaml
@@ -23,32 +23,22 @@ inputs:
 runs:
   using: "composite"
   steps:
-    - name: Force remove conflicting Docker packages
+    - name: Install Infisical CLI
       shell: bash
       run: |
-        sudo dpkg --purge --force-all containerd || true
-        sudo dpkg --purge --force-all containerd.io || true
-        sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
-        sudo apt-get purge -y docker-ce docker-ce-cli containerd.io || true
-        sudo apt-get autoremove -y
-        sudo apt-get autoclean -y
-
-    - name: Clear and update APT cache
+        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
+        sudo apt-get update && sudo apt-get install -y infisical
+    
+    - name: Authenticate with Infisical
       shell: bash
       run: |
-        sudo rm -rf /var/lib/apt/lists/*
-        sudo apt-get clean
-        sudo apt-get update
+        echo "INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=${{ inputs.infisical_client_id }} --client-secret=${{ inputs.infisical_client_secret }} --silent --plain)" >> $GITHUB_ENV
 
-    - name: Manually install Docker and dependencies
+    - name: Install Docker
       shell: bash
       run: |
-        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
-        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
-        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
-        sudo apt-get update
-        sudo apt-get install -y docker-ce docker-ce-cli containerd.io
-
+        apt install docker.io -y
+    
     - name: Login to Docker Hub
       uses: docker/login-action@v3
       with:
@@ -58,42 +48,31 @@ runs:
     - name: Pull Docker Image
       shell: bash
       run: docker pull ${{ inputs.docker_image }}
+    
+    # - name: Check System Resources
+    #   shell: bash
+    #   run: |
+    #     MEM_AVAILABLE=$(free -m | awk '/^Mem:/{print $7}')
+    #     DISK_AVAILABLE=$(df -m / | awk 'NR==2 {print $4}')
+    #     if [ "$MEM_AVAILABLE" -lt 512 ]; then
+    #       echo "Insufficient memory to initialize Docker Swarm. Available: ${MEM_AVAILABLE}MB"
+    #       exit 1
+    #     fi
+    #     if [ "$DISK_AVAILABLE" -lt 1024 ]; then
+    #       echo "Insufficient disk space to deploy Docker service. Available: ${DISK_AVAILABLE}MB"
+    #       exit 1
+    #     fi
 
-    - name: Install Infisical CLI
-      shell: bash
-      run: |
-        curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo -E bash
-        sudo apt-get update && sudo apt-get install -y infisical
-
-    - name: Authenticate with Infisical
-      shell: bash
-      run: |
-        echo "INFISICAL_TOKEN=$(infisical login --method=universal-auth --client-id=${{ inputs.infisical_client_id }} --client-secret=${{ inputs.infisical_client_secret }} --silent --plain)" >> $GITHUB_ENV
-
-    - name: Check System Resources
-      shell: bash
-      run: |
-        MEM_AVAILABLE=$(free -m | awk '/^Mem:/{print $7}')
-        DISK_AVAILABLE=$(df -m / | awk 'NR==2 {print $4}')
-        if [ "$MEM_AVAILABLE" -lt 512 ]; then
-          echo "Insufficient memory to initialize Docker Swarm. Available: ${MEM_AVAILABLE}MB"
-          exit 1
-        fi
-        if [ "$DISK_AVAILABLE" -lt 1024 ]; then
-          echo "Insufficient disk space to deploy Docker service. Available: ${DISK_AVAILABLE}MB"
-          exit 1
-        fi
-
-    - name: Check Firewall Configuration
-      shell: bash
-      run: |
-        REQUIRED_PORTS=(2377 7946 4789)
-        for PORT in "${REQUIRED_PORTS[@]}"; do
-          if ! sudo ufw status | grep -q "$PORT"; then
-            echo "Port $PORT is not open. Configuring firewall."
-            sudo ufw allow $PORT
-          fi
-        done
+    # - name: Check Firewall Configuration
+    #   shell: bash
+    #   run: |
+    #     REQUIRED_PORTS=(2377 7946 4789)
+    #     for PORT in "${REQUIRED_PORTS[@]}"; do
+    #       if ! sudo ufw status | grep -q "$PORT"; then
+    #         echo "Port $PORT is not open. Configuring firewall."
+    #         sudo ufw allow $PORT
+    #       fi
+    #     done
 
     - name: Initialize Docker Swarm Manager
       shell: bash
@@ -109,17 +88,17 @@ runs:
         fi
         echo "MANAGER_TOKEN=$(docker swarm join-token -q manager)" >> $GITHUB_ENV
 
-    - name: Retry Swarm Initialization if Inactive
-      shell: bash
-      run: |
-        if [ "$(docker info --format '{{.Swarm.LocalNodeState}}')" != "active" ]; then
-          echo "Swarm inactive. Retrying initialization..."
-          docker swarm init --advertise-addr $(hostname -I | awk '{print $1}') --listen-addr 0.0.0.0:2377
-          if [ "$(docker info --format '{{.Swarm.LocalNodeState}}')" != "active" ]; then
-            echo "Failed to initialize Docker Swarm after retry."
-            exit 1
-          fi
-        fi
+    # - name: Retry Swarm Initialization if Inactive
+    #   shell: bash
+    #   run: |
+    #     if [ "$(docker info --format '{{.Swarm.LocalNodeState}}')" != "active" ]; then
+    #       echo "Swarm inactive. Retrying initialization..."
+    #       docker swarm init --advertise-addr $(hostname -I | awk '{print $1}') --listen-addr 0.0.0.0:2377
+    #       if [ "$(docker info --format '{{.Swarm.LocalNodeState}}')" != "active" ]; then
+    #         echo "Failed to initialize Docker Swarm after retry."
+    #         exit 1
+    #       fi
+    #     fi
 
     - name: Retrieve Docker Swarm CA Fingerprint
       shell: bash
